version: 2

defaults: &defaults
  working_directory: ~/workspace
  machine: true

only-publish-tags: &only-publish-tags
  filters:
    tags:
      only: /^v?\d+\.\d+\.\d+$/
    branches:
      ignore: /.*/

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: |
            set +e
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            nvm install v12.13.0
            nvm alias default v12.13.0
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package.json" }}-v2
            - node-modules-v2
      - run: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            npm install
      - save_cache:
          paths:
            - node_modules
          key: node-modules-{{ checksum "package.json" }}-v2
      - run: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            npx roboter
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - .
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/workspace
      - run: |
            set +e
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            nvm install v12.13.0
            nvm alias default v12.13.0
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/workspace/.npmrc
      - run: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            npx roboter build
            npm publish

workflows:
  version: 2
  untagged-build:
    jobs:
      - build
  tagged-build:
    jobs:
      - build: *only-publish-tags
      - publish:
          <<: *only-publish-tags
          requires:
            - build
          context: Default
