name: Release

on:
  push:
    branches:
      - 'master'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Update Ubuntu
      run: |
        sudo apt-get update
        sudo apt-get install -y libgbm-dev
    - uses: actions/checkout@v1
    - name: Cache node_modules
      id: cache-modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('package.json') }}
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      if: steps.cache-modules.outputs.cache-hit != 'true'
      run: |
        npm ci
    - name: Run roboter
      run: |
        npx roboter
    - name: Compile TypeScript
      run: |
        npx roboter build
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN_ADMIN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN_ADMIN }}
      run: npx semantic-release
